services:
  db:
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: foro_hub
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      DB_URL: jdbc:mysql://db:3306/foro_hub?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      DB_USER: root
      DB_PASS: changeme
    ports:
      - "8080:8080"
